# Generated by Django 3.2.4 on 2024-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('signal_strength', models.IntegerField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_ask', models.BooleanField(default=False)),
            ],
        ),
    ]
