# Generated by Django 3.2.4 on 2024-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_locationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='signal_strength',
            field=models.FloatField(),
        ),
    ]
