# Generated by Django 3.2.4 on 2024-03-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_locationdata_signal_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='Network',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='Operator',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='Users',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
