# Generated by Django 3.2.4 on 2024-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240408_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='Time',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
